public class SconosciutoBattleDefine {
	public enum Idx {
		Scnoo_SubShotFollowThrow_copy = 0
		,Scono_AirDash_copy = 1
		,Scono_Arousal_copy = 2
		,Scono_backexwrestle_copy = 3
		,Scono_backstep_back_copy = 4
		,Scono_backstep_copy = 5
		,Scono_backwrestle_copy = 6
		,Scono_bdwrestle_copy = 7
		,Scono_Damage_copy = 8
		,Scono_Down_copy = 9
		,Scono_EXShotFollowThrow_copy = 10
		,Scono_exwrestle_copy = 11
		,Scono_frontexwrestle_copy = 12
		,Scono_frontstep_back_copy = 13
		,Scono_frontstep_copy = 14
		,Scono_frontwrestle_copy = 15
		,Scono_jump_copy = 16
		,Scono_jump_under_only_copy = 17
		,Scono_jumping_copy = 18
		,Scono_jumping_under_only_copy = 19
		,Scono_landing_copy = 20
		,Scono_leftstep_back_copy = 21
		,Scono_leftstep_copy = 22
		,Scono_leftwrestle_copy = 23
		,Scono_neutral_copy = 24
		,Scono_normalshot_copy = 25
		,Scono_pay_an_arm_copy = 26
		,Scono_put_hand_ahead_copy = 27
		,Scono_rebirsal_copy = 28
		,Scono_rightstep_back_copy = 29
		,Scono_rightstep_copy = 30
		,Scono_rightwrestle_copy = 31
		,Scono_run_copy = 32
		,scono_RunShot = 33
		,Scono_ShotFollowThrow_top_only_copy = 34
		,Scono_SpinDown_copy = 35
		,Scono_subshot_copy = 36
		,Scono_walk_copy = 37
		,Scono_Walk_under_only_copy = 38
		,Scono_Wrestle1_copy = 39
		,Scono_wrestle3_copy = 40
		,Scono_Wrestle2_copy = 41
		,scono_RunShotFollowThrow = 42
		, Scono_fall_copy = 43
		, SIZE = 44
	}
}
